/**
 *  You start server → node index.js
        ↓
    Express server start hota hai
            ↓
    Form.io attach hota hai
            ↓
    MongoDB connect hota hai
            ↓
    Auto APIs create ho jati hain
            ↓
    Frontend + Seed script use those APIs

 * Form.io Self-Hosted Backend Server
 * ====================================
 * This file boots up the Form.io server using the official `formio` npm package.
 * Form.io handles ALL of the following automatically:
 *  - MongoDB connection & schema management
 *  - REST API for forms, submissions, roles, users
 *  - JWT-based authentication
 *  - Form validation
 *
 * Key API Endpoints (auto-generated by Form.io):
 *  POST   /user/login                  → Get JWT token
 *  POST   /form                        → Create a new form
 *  GET    /form                        → List all forms
 *  GET    /form/:formId               → Get form schema
 *  PUT    /form/:formId               → Update form
 *  DELETE /form/:formId               → Delete form
 *  POST   /form/:formId/submission    → Submit data to a form
 *  GET    /form/:formId/submission    → Get all submissions
 *  GET    /form/:formId/submission/:id → Get single submission
 *
 * How Form.io stores data in MongoDB:
 *  - Forms are stored in the `forms` collection
 *  - Each form's submissions go into the `submissions` collection
 *  - The submission document contains { form: <formId>, data: { ...yourFormData } }
 *  - Users/roles are in `roles` and `users` collections
 */

require('dotenv').config();
const express = require('express');
const cors = require('cors');

// Add mongoose and set strictQuery to suppress deprecation warning
const mongoose = require('mongoose');
mongoose.set('strictQuery', true);

const app = express();

// ─── CORS — allow the React frontend ─────────────────────────────────────────
app.use(cors({
  origin: ['http://localhost:5173', 'http://localhost:3000'],
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization', 'x-jwt-token'],
  credentials: true,
}));

// ─── Body parsing ─────────────────────────────────────────────────────────────
// 👉 JSON request read karega
app.use(express.json({ limit: '10mb' }));
// 👉 Form data read karega
app.use(express.urlencoded({ extended: true }));

// ─── Health check (before Form.io takes over routing) ────────────────────────
app.get('/health', (req, res) => {
  res.json({
    status: 'ok',
    message: 'Form.io backend is running',
    timestamp: new Date().toISOString(),
    mongodb: process.env.MONGO_URI,
  });
});

// ─── Boot Form.io Server ──────────────────────────────────────────────────────
//
// IMPORTANT: formio(config) API works in TWO steps:
//   Step 1: formio(config)  → returns the Express router immediately (NOT a Promise)
//   Step 2: router.init()   → returns a Q Promise that resolves when MongoDB is ready
//
const formio = require('formio');

const config = {
  mongo: process.env.MONGO_URI,
  jwt: {
    // Required for Form.io to generate/validate `x-jwt-token`.
    secret: process.env.JWT_SECRET || 'supersecretkey123',
    expireTime: 240, // hours
  },
  // Email (disabled for local dev)
  email: {
    transport: 'stub',
  },
  // ← REQUIRED: root credentials for first-run admin setup
  // Without this, Form.io silently skips creating the admin user!
  root: {
    email:    process.env.ADMIN_EMAIL,
    password: process.env.ADMIN_PASS,
  },
};

// Step 1: Get the Express router from formio (synchronous)
const formioRouter = formio(config);

// ─── Auto-Seed: Spawn seed/createForm.js after server is fully ready ─────────
const { spawn } = require('child_process');
const path = require('path');

function autoSeedForm() {
  const seedScript = path.join(__dirname, 'seed', 'createForm.js');
  const child = spawn(process.execPath, [seedScript], {
    cwd: __dirname,
    env: process.env,
    stdio: 'inherit', // pipe output directly to this terminal
  });
  child.on('exit', (code) => {
    if (code !== 0) {
      console.log('  ⚠️  Seed script exited with code ' + code + ' (non-fatal).');
    }
  });
}

// Step 2: Call router.init() — THIS returns the Promise
formioRouter.init().then(() => {
  // Mount Form.io on root — all /form, /user, /role, /submission routes come from here
  app.use('/', formioRouter);

  const PORT = process.env.PORT || 3001;

  app.listen(PORT, () => {
    console.log('');
    console.log('╔══════════════════════════════════════════════════╗');
    console.log('║      Form.io Self-Hosted Server — Started        ║');
    console.log('╠══════════════════════════════════════════════════╣');
    console.log(`║  🚀 API running at : http://localhost:${PORT}       ║`);
    console.log(`║  🗄️  MongoDB       : ${process.env.MONGO_URI.split('/').pop().padEnd(20)} ║`);
    console.log('║                                                  ║');
    console.log('║  Useful endpoints:                               ║');
    console.log('║   GET  /health           → health check          ║');
    console.log('║   POST /user/login       → get JWT token         ║');
    console.log('║   POST /form             → create form           ║');
    console.log('║   GET  /form             → list all forms        ║');
    console.log('║   POST /form/:id/submission → submit data        ║');
    console.log('║   GET  /form/:id/submission → fetch submissions  ║');
    console.log('╚══════════════════════════════════════════════════╝');
    console.log('');
    console.log('  ℹ️  Admin email : ' + (process.env.ADMIN_EMAIL || 'admin@example.com'));
    console.log('  🔧 Auto-seeding Employee Form...');
    console.log('');

    // Wait a moment for Form.io to fully settle, then auto-seed
    setTimeout(autoSeedForm, 1500);
  });
}).catch((err) => {
  console.error('❌ Failed to start Form.io server:', err.message);
  console.error(err);
  process.exit(1);
});

